CREATE SCHEMA IF NOT EXISTS ASSIGN;
SET SCHEMA =  ASSIGN;
CREATE TABLE IF NOT EXISTS
DATA(
ID LONG(5) AUTO_INCREMENT,
CATEGORY_CODE VARCHAR(10),
C_VALUES VARCHAR,
UPDATED_DATE DATE,
UPDATED_TS TIMESTAMP
);